### ISSUE TITLE
OhSender Status state variable

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohSongcast#4]
The [developer page](http://wiki.openhome.org/wiki/Developer:SenderService) of the Sender Service shows the following state variables:

- Sending - currently sending audio over the network
- Ready - ready to send audio but no listeners
- Blocked - audio from another sender detected on the same channel (mis-configuration)
- Inactive - no audio source currently assigned to this sender
- Disabled - sender disabled by user configuration

However, the [OhmSender](https://github.com/openhome/ohSongcast/blob/cebd02c94c77468b883e63213b5f891009c33515/OhmSender.cpp#L160-L162) implementation defines "Enabled", "Disabled", and "Blocked".

**Comment by SimonChisholm** [comment]
I'll fix this soon for the ohPipeline repo.  The Sender implementation for this repo is not being actively maintained so will likely take a bit longer to be changed

**Comment by joerg-krause** [comment]
Closed because it is ancient.
