### ISSUE TITLE
OhmSender creates new UPnP device, but OhmReceiver does not

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohSongcast#5]
Why does the OhmSender creates a new UPnP device, whereas the OhmReceiver does not? This way, the Receiver service is included in the MediaRenderer device, whereas the Sender service is included in the Sender device.

![image](https://cloud.githubusercontent.com/assets/6870896/24951589/3726a17e-1f75-11e7-9915-b33ea36ebfa4.png)

**Comment by SimonChisholm** [comment]
The ohSongcast repo is used for a pc-based sender.  This code is a little out of date now.  See the ohPipeline repo for an implementation of Sender and Receiver that are both available from the same UPnP device.

**Comment by joerg-krause** [comment]
Good to know! I'll try with the sources from the ohPipeline repo, thanks!
